# FROM daewok/sbcl:alpine
FROM alpine:latest

# RUN apk --update
RUN mkdir /root/my-portfolio
COPY ./static /root/my-portfolio/static
COPY ./builds/my-portfolio.exe /root/my-portfolio.exe

WORKDIR /root

ENTRYPOINT ["sh"]
# ENTRYPOINT ["/root/my-portfolio.exe"]
