version: '3.7'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
  my-portfolio:
    image: emactaggart/my-portfolio:latest
    container_name: my-portfolio
    ports:
      - 8080:8080
    volumes:
      - ~/prod.taggrc:/root/.taggrc:ro
      - /var/log/my-portfolio:/var/log/my-portfolio
