version: "3.7"
services:
  lisp-base:
    image: emactaggart/lisp-base:alpine
    container_name: lisp-base
    build:
      context: .
      dockerfile: Dockerfile.lisp-base
  my-portfolio-base:
    image: emactaggart/my-portfolio-base:alpine
    container_name: my-portfolio-base
    build:
      context: .
      dockerfile: Dockerfile.my-portfolio-base
  make-prod-executable:
    image: emactaggart/my-portfolio-base:alpine
    container_name: my-portfolio-build-prod-executable
    command: "make build"
    volumes:
      - ./builds:/root/my-portfolio/builds
  build-prod:
    image: emactaggart/my-portfolio:latest
    container_name: my-portfolio-build-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
  docker-test:
    image: emactaggart/my-portfolio-base:alpine
    container_name: my-portfolio-test
    command: "make test"

