FROM emactaggart/lisp-base:alpine

COPY ./ /root/my-portfolio/
RUN ln -s /root/my-portfolio/my-portfolio.asd /root/quicklisp/local-projects/

EXPOSE 8080

WORKDIR /root/my-portfolio

# Esentially caches the project and test dependencies in this docker image
RUN sbcl --non-interactive \
  --eval "(ql:quickload :my-portfolio)" \
  --eval "(ql:quickload :my-portfolio/tests)"

ENTRYPOINT ["sh", "-c"]
