version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
  portfolio:
    image: emactaggart/my-portfolio
    container_name: my-portfolio
    ports:
      - 8080:8080
    volumes:
      - ~/prod.taggrc:/root/.taggrc:ro
      - /var/log/my-portfolio:/var/log/my-portfolio
    # stdin_open: true
    tty: true
